// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/test/_404.tsx";
import * as $1 from "./routes/test/_app.tsx";
import * as $2 from "./routes/test/_middleware.tsx";
import * as $3 from "./routes/test/api/joke.ts";
import * as $4 from "./routes/test/greet/[name].tsx";
import * as $5 from "./routes/test/index.tsx";
import * as $$0 from "./islands/Counter.tsx";

const manifest = {
  routes: {
    "./routes/test/_404.tsx": $0,
    "./routes/test/_app.tsx": $1,
    "./routes/test/_middleware.tsx": $2,
    "./routes/test/api/joke.ts": $3,
    "./routes/test/greet/[name].tsx": $4,
    "./routes/test/index.tsx": $5,
  },
  islands: {
    "./islands/Counter.tsx": $$0,
  },
  baseUrl: import.meta.url,
};

export default manifest;
